#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/uart.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_7

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_13
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_4
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_3
#define AUDIO_CODEC_ES8311_ADDR  0x18

#define BOOT_BUTTON_GPIO        GPIO_NUM_9

#define YT2228_UART_NUM         UART_NUM_1
#define YT2228_TX_PIN           GPIO_NUM_20
#define YT2228_RX_PIN           GPIO_NUM_21
#define YT2228_BAUD_RATE        9600

#define SHUTDOWN_GPIO           GPIO_NUM_1

#endif // _BOARD_CONFIG_H_
